import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
import Navbar from '@/app/components/Navbar'
import Provider from './components/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-white text-black dark:bg-[#083344] dark:text-white h-full 
        `}>
          <Provider>
        <Navbar />
        <main className='max-w-6xl px-4 mx-auto sm:px-6 lg:px-8'>
          {children}
        </main>
        </Provider>
      </body>
    </html>
  )
}
